<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class CountriesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $now = Carbon::now();

        $countries = [
            [
                'name' => 'United States',
                'code' => 'US',
                'code3' => 'USA',
                'numeric_code' => '840',
                'phone_code' => '1',
                'capital' => 'Washington D.C.',
                'currency' => 'US Dollar',
                'currency_code' => 'USD',
                'currency_symbol' => '$',
                'region' => 'Americas',
                'subregion' => 'North America',
                'timezone' => 'America/New_York',
                'timezones' => json_encode([
                    'America/New_York', 'America/Chicago', 'America/Denver', 'America/Los_Angeles',
                    'America/Anchorage', 'America/Adak', 'Pacific/Honolulu'
                ]),
                'timezone_offset' => '-05:00',
                'has_dst' => true,
                'latitude' => 37.09024,
                'longitude' => -95.712891,
                'emoji' => '🇺🇸',
                'active' => true,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'name' => 'United Kingdom',
                'code' => 'GB',
                'code3' => 'GBR',
                'numeric_code' => '826',
                'phone_code' => '44',
                'capital' => 'London',
                'currency' => 'British Pound',
                'currency_code' => 'GBP',
                'currency_symbol' => '£',
                'region' => 'Europe',
                'subregion' => 'Northern Europe',
                'timezone' => 'Europe/London',
                'timezones' => json_encode(['Europe/London']),
                'timezone_offset' => '+00:00',
                'has_dst' => true,
                'latitude' => 55.378051,
                'longitude' => -3.435973,
                'emoji' => '🇬🇧',
                'active' => true,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'name' => 'Canada',
                'code' => 'CA',
                'code3' => 'CAN',
                'numeric_code' => '124',
                'phone_code' => '1',
                'capital' => 'Ottawa',
                'currency' => 'Canadian Dollar',
                'currency_code' => 'CAD',
                'currency_symbol' => '$',
                'region' => 'Americas',
                'subregion' => 'North America',
                'timezone' => 'America/Toronto',
                'timezones' => json_encode([
                    'America/St_Johns', 'America/Halifax', 'America/Toronto',
                    'America/Winnipeg', 'America/Edmonton', 'America/Vancouver'
                ]),
                'timezone_offset' => '-05:00',
                'has_dst' => true,
                'latitude' => 56.130366,
                'longitude' => -106.346771,
                'emoji' => '🇨🇦',
                'active' => true,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'name' => 'Australia',
                'code' => 'AU',
                'code3' => 'AUS',
                'numeric_code' => '036',
                'phone_code' => '61',
                'capital' => 'Canberra',
                'currency' => 'Australian Dollar',
                'currency_code' => 'AUD',
                'currency_symbol' => '$',
                'region' => 'Oceania',
                'subregion' => 'Australia and New Zealand',
                'timezone' => 'Australia/Sydney',
                'timezones' => json_encode([
                    'Australia/Sydney', 'Australia/Melbourne', 'Australia/Brisbane',
                    'Australia/Adelaide', 'Australia/Darwin', 'Australia/Perth'
                ]),
                'timezone_offset' => '+10:00',
                'has_dst' => true,
                'latitude' => -25.274398,
                'longitude' => 133.775136,
                'emoji' => '🇦🇺',
                'active' => true,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'name' => 'Germany',
                'code' => 'DE',
                'code3' => 'DEU',
                'numeric_code' => '276',
                'phone_code' => '49',
                'capital' => 'Berlin',
                'currency' => 'Euro',
                'currency_code' => 'EUR',
                'currency_symbol' => '€',
                'region' => 'Europe',
                'subregion' => 'Western Europe',
                'timezone' => 'Europe/Berlin',
                'timezones' => json_encode(['Europe/Berlin']),
                'timezone_offset' => '+01:00',
                'has_dst' => true,
                'latitude' => 51.165691,
                'longitude' => 10.451526,
                'emoji' => '🇩🇪',
                'active' => true,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'name' => 'France',
                'code' => 'FR',
                'code3' => 'FRA',
                'numeric_code' => '250',
                'phone_code' => '33',
                'capital' => 'Paris',
                'currency' => 'Euro',
                'currency_code' => 'EUR',
                'currency_symbol' => '€',
                'region' => 'Europe',
                'subregion' => 'Western Europe',
                'timezone' => 'Europe/Paris',
                'timezones' => json_encode(['Europe/Paris']),
                'timezone_offset' => '+01:00',
                'has_dst' => true,
                'latitude' => 46.227638,
                'longitude' => 2.213749,
                'emoji' => '🇫🇷',
                'active' => true,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'name' => 'Japan',
                'code' => 'JP',
                'code3' => 'JPN',
                'numeric_code' => '392',
                'phone_code' => '81',
                'capital' => 'Tokyo',
                'currency' => 'Japanese Yen',
                'currency_code' => 'JPY',
                'currency_symbol' => '¥',
                'region' => 'Asia',
                'subregion' => 'Eastern Asia',
                'timezone' => 'Asia/Tokyo',
                'timezones' => json_encode(['Asia/Tokyo']),
                'timezone_offset' => '+09:00',
                'has_dst' => false,
                'latitude' => 36.204824,
                'longitude' => 138.252924,
                'emoji' => '🇯🇵',
                'active' => true,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'name' => 'India',
                'code' => 'IN',
                'code3' => 'IND',
                'numeric_code' => '356',
                'phone_code' => '91',
                'capital' => 'New Delhi',
                'currency' => 'Indian Rupee',
                'currency_code' => 'INR',
                'currency_symbol' => '₹',
                'region' => 'Asia',
                'subregion' => 'Southern Asia',
                'timezone' => 'Asia/Kolkata',
                'timezones' => json_encode(['Asia/Kolkata']),
                'timezone_offset' => '+05:30',
                'has_dst' => false,
                'latitude' => 20.593684,
                'longitude' => 78.96288,
                'emoji' => '🇮🇳',
                'active' => true,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'name' => 'China',
                'code' => 'CN',
                'code3' => 'CHN',
                'numeric_code' => '156',
                'phone_code' => '86',
                'capital' => 'Beijing',
                'currency' => 'Chinese Yuan',
                'currency_code' => 'CNY',
                'currency_symbol' => '¥',
                'region' => 'Asia',
                'subregion' => 'Eastern Asia',
                'timezone' => 'Asia/Shanghai',
                'timezones' => json_encode(['Asia/Shanghai', 'Asia/Urumqi']),
                'timezone_offset' => '+08:00',
                'has_dst' => false,
                'latitude' => 35.86166,
                'longitude' => 104.195397,
                'emoji' => '🇨🇳',
                'active' => true,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'name' => 'Brazil',
                'code' => 'BR',
                'code3' => 'BRA',
                'numeric_code' => '076',
                'phone_code' => '55',
                'capital' => 'Brasília',
                'currency' => 'Brazilian Real',
                'currency_code' => 'BRL',
                'currency_symbol' => 'R$',
                'region' => 'Americas',
                'subregion' => 'South America',
                'timezone' => 'America/Sao_Paulo',
                'timezones' => json_encode(['America/Sao_Paulo', 'America/Manaus', 'America/Rio_Branco']),
                'timezone_offset' => '-03:00',
                'has_dst' => true,
                'latitude' => -14.235004,
                'longitude' => -51.92528,
                'emoji' => '🇧🇷',
                'active' => true,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'name' => 'Nigeria',
                'code' => 'NG',
                'code3' => 'NGA',
                'numeric_code' => '566',
                'phone_code' => '234',
                'capital' => 'Abuja',
                'currency' => 'Nigerian Naira',
                'currency_code' => 'NGN',
                'currency_symbol' => '₦',
                'region' => 'Africa',
                'subregion' => 'Western Africa',
                'timezone' => 'Africa/Lagos',
                'timezones' => json_encode(['Africa/Lagos']),
                'timezone_offset' => '+01:00',
                'has_dst' => false,
                'latitude' => 9.081999,
                'longitude' => 8.675277,
                'emoji' => '🇳🇬',
                'active' => true,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'name' => 'South Africa',
                'code' => 'ZA',
                'code3' => 'ZAF',
                'numeric_code' => '710',
                'phone_code' => '27',
                'capital' => 'Pretoria',
                'currency' => 'South African Rand',
                'currency_code' => 'ZAR',
                'currency_symbol' => 'R',
                'region' => 'Africa',
                'subregion' => 'Southern Africa',
                'timezone' => 'Africa/Johannesburg',
                'timezones' => json_encode(['Africa/Johannesburg']),
                'timezone_offset' => '+02:00',
                'has_dst' => false,
                'latitude' => -30.559482,
                'longitude' => 22.937506,
                'emoji' => '🇿🇦',
                'active' => true,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'name' => 'Mexico',
                'code' => 'MX',
                'code3' => 'MEX',
                'numeric_code' => '484',
                'phone_code' => '52',
                'capital' => 'Mexico City',
                'currency' => 'Mexican Peso',
                'currency_code' => 'MXN',
                'currency_symbol' => '$',
                'region' => 'Americas',
                'subregion' => 'North America',
                'timezone' => 'America/Mexico_City',
                'timezones' => json_encode(['America/Mexico_City', 'America/Tijuana', 'America/Cancun']),
                'timezone_offset' => '-06:00',
                'has_dst' => true,
                'latitude' => 23.634501,
                'longitude' => -102.552784,
                'emoji' => '🇲🇽',
                'active' => true,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'name' => 'Spain',
                'code' => 'ES',
                'code3' => 'ESP',
                'numeric_code' => '724',
                'phone_code' => '34',
                'capital' => 'Madrid',
                'currency' => 'Euro',
                'currency_code' => 'EUR',
                'currency_symbol' => '€',
                'region' => 'Europe',
                'subregion' => 'Southern Europe',
                'timezone' => 'Europe/Madrid',
                'timezones' => json_encode(['Europe/Madrid', 'Atlantic/Canary']),
                'timezone_offset' => '+01:00',
                'has_dst' => true,
                'latitude' => 40.463667,
                'longitude' => -3.74922,
                'emoji' => '🇪🇸',
                'active' => true,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'name' => 'Italy',
                'code' => 'IT',
                'code3' => 'ITA',
                'numeric_code' => '380',
                'phone_code' => '39',
                'capital' => 'Rome',
                'currency' => 'Euro',
                'currency_code' => 'EUR',
                'currency_symbol' => '€',
                'region' => 'Europe',
                'subregion' => 'Southern Europe',
                'timezone' => 'Europe/Rome',
                'timezones' => json_encode(['Europe/Rome']),
                'timezone_offset' => '+01:00',
                'has_dst' => true,
                'latitude' => 41.87194,
                'longitude' => 12.56738,
                'emoji' => '🇮🇹',
                'active' => true,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'name' => 'Russia',
                'code' => 'RU',
                'code3' => 'RUS',
                'numeric_code' => '643',
                'phone_code' => '7',
                'capital' => 'Moscow',
                'currency' => 'Russian Ruble',
                'currency_code' => 'RUB',
                'currency_symbol' => '₽',
                'region' => 'Europe',
                'subregion' => 'Eastern Europe',
                'timezone' => 'Europe/Moscow',
                'timezones' => json_encode([
                    'Europe/Kaliningrad', 'Europe/Moscow', 'Europe/Samara',
                    'Asia/Yekaterinburg', 'Asia/Omsk', 'Asia/Krasnoyarsk',
                    'Asia/Irkutsk', 'Asia/Yakutsk', 'Asia/Vladivostok',
                    'Asia/Magadan', 'Asia/Kamchatka'
                ]),
                'timezone_offset' => '+03:00',
                'has_dst' => false,
                'latitude' => 61.52401,
                'longitude' => 105.318756,
                'emoji' => '🇷🇺',
                'active' => true,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'name' => 'Singapore',
                'code' => 'SG',
                'code3' => 'SGP',
                'numeric_code' => '702',
                'phone_code' => '65',
                'capital' => 'Singapore',
                'currency' => 'Singapore Dollar',
                'currency_code' => 'SGD',
                'currency_symbol' => '$',
                'region' => 'Asia',
                'subregion' => 'South-Eastern Asia',
                'timezone' => 'Asia/Singapore',
                'timezones' => json_encode(['Asia/Singapore']),
                'timezone_offset' => '+08:00',
                'has_dst' => false,
                'latitude' => 1.352083,
                'longitude' => 103.819836,
                'emoji' => '🇸🇬',
                'active' => true,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'name' => 'United Arab Emirates',
                'code' => 'AE',
                'code3' => 'ARE',
                'numeric_code' => '784',
                'phone_code' => '971',
                'capital' => 'Abu Dhabi',
                'currency' => 'United Arab Emirates Dirham',
                'currency_code' => 'AED',
                'currency_symbol' => 'د.إ',
                'region' => 'Asia',
                'subregion' => 'Western Asia',
                'timezone' => 'Asia/Dubai',
                'timezones' => json_encode(['Asia/Dubai']),
                'timezone_offset' => '+04:00',
                'has_dst' => false,
                'latitude' => 23.424076,
                'longitude' => 53.847818,
                'emoji' => '🇦🇪',
                'active' => true,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'name' => 'Saudi Arabia',
                'code' => 'SA',
                'code3' => 'SAU',
                'numeric_code' => '682',
                'phone_code' => '966',
                'capital' => 'Riyadh',
                'currency' => 'Saudi Riyal',
                'currency_code' => 'SAR',
                'currency_symbol' => '﷼',
                'region' => 'Asia',
                'subregion' => 'Western Asia',
                'timezone' => 'Asia/Riyadh',
                'timezones' => json_encode(['Asia/Riyadh']),
                'timezone_offset' => '+03:00',
                'has_dst' => false,
                'latitude' => 23.885942,
                'longitude' => 45.079162,
                'emoji' => '🇸🇦',
                'active' => true,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'name' => 'South Korea',
                'code' => 'KR',
                'code3' => 'KOR',
                'numeric_code' => '410',
                'phone_code' => '82',
                'capital' => 'Seoul',
                'currency' => 'South Korean Won',
                'currency_code' => 'KRW',
                'currency_symbol' => '₩',
                'region' => 'Asia',
                'subregion' => 'Eastern Asia',
                'timezone' => 'Asia/Seoul',
                'timezones' => json_encode(['Asia/Seoul']),
                'timezone_offset' => '+09:00',
                'has_dst' => false,
                'latitude' => 35.907757,
                'longitude' => 127.766922,
                'emoji' => '🇰🇷',
                'active' => true,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'name' => 'Netherlands',
                'code' => 'NL',
                'code3' => 'NLD',
                'numeric_code' => '528',
                'phone_code' => '31',
                'capital' => 'Amsterdam',
                'currency' => 'Euro',
                'currency_code' => 'EUR',
                'currency_symbol' => '€',
                'region' => 'Europe',
                'subregion' => 'Western Europe',
                'timezone' => 'Europe/Amsterdam',
                'timezones' => json_encode(['Europe/Amsterdam']),
                'timezone_offset' => '+01:00',
                'has_dst' => true,
                'latitude' => 52.132633,
                'longitude' => 5.291266,
                'emoji' => '🇳🇱',
                'active' => true,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'name' => 'Sweden',
                'code' => 'SE',
                'code3' => 'SWE',
                'numeric_code' => '752',
                'phone_code' => '46',
                'capital' => 'Stockholm',
                'currency' => 'Swedish Krona',
                'currency_code' => 'SEK',
                'currency_symbol' => 'kr',
                'region' => 'Europe',
                'subregion' => 'Northern Europe',
                'timezone' => 'Europe/Stockholm',
                'timezones' => json_encode(['Europe/Stockholm']),
                'timezone_offset' => '+01:00',
                'has_dst' => true,
                'latitude' => 60.128161,
                'longitude' => 18.643501,
                'emoji' => '🇸🇪',
                'active' => true,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'name' => 'Norway',
                'code' => 'NO',
                'code3' => 'NOR',
                'numeric_code' => '578',
                'phone_code' => '47',
                'capital' => 'Oslo',
                'currency' => 'Norwegian Krone',
                'currency_code' => 'NOK',
                'currency_symbol' => 'kr',
                'region' => 'Europe',
                'subregion' => 'Northern Europe',
                'timezone' => 'Europe/Oslo',
                'timezones' => json_encode(['Europe/Oslo']),
                'timezone_offset' => '+01:00',
                'has_dst' => true,
                'latitude' => 60.472024,
                'longitude' => 8.468946,
                'emoji' => '🇳🇴',
                'active' => true,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'name' => 'New Zealand',
                'code' => 'NZ',
                'code3' => 'NZL',
                'numeric_code' => '554',
                'phone_code' => '64',
                'capital' => 'Wellington',
                'currency' => 'New Zealand Dollar',
                'currency_code' => 'NZD',
                'currency_symbol' => '$',
                'region' => 'Oceania',
                'subregion' => 'Australia and New Zealand',
                'timezone' => 'Pacific/Auckland',
                'timezones' => json_encode(['Pacific/Auckland', 'Pacific/Chatham']),
                'timezone_offset' => '+12:00',
                'has_dst' => true,
                'latitude' => -40.900557,
                'longitude' => 174.885971,
                'emoji' => '🇳🇿',
                'active' => true,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'name' => 'Switzerland',
                'code' => 'CH',
                'code3' => 'CHE',
                'numeric_code' => '756',
                'phone_code' => '41',
                'capital' => 'Bern',
                'currency' => 'Swiss Franc',
                'currency_code' => 'CHF',
                'currency_symbol' => 'CHF',
                'region' => 'Europe',
                'subregion' => 'Western Europe',
                'timezone' => 'Europe/Zurich',
                'timezones' => json_encode(['Europe/Zurich']),
                'timezone_offset' => '+01:00',
                'has_dst' => true,
                'latitude' => 46.818188,
                'longitude' => 8.227512,
                'emoji' => '🇨🇭',
                'active' => true,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'name' => 'Argentina',
                'code' => 'AR',
                'code3' => 'ARG',
                'numeric_code' => '032',
                'phone_code' => '54',
                'capital' => 'Buenos Aires',
                'currency' => 'Argentine Peso',
                'currency_code' => 'ARS',
                'currency_symbol' => '$',
                'region' => 'Americas',
                'subregion' => 'South America',
                'timezone' => 'America/Argentina/Buenos_Aires',
                'timezones' => json_encode(['America/Argentina/Buenos_Aires']),
                'timezone_offset' => '-03:00',
                'has_dst' => false,
                'latitude' => -38.416097,
                'longitude' => -63.616672,
                'emoji' => '🇦🇷',
                'active' => true,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'name' => 'Ireland',
                'code' => 'IE',
                'code3' => 'IRL',
                'numeric_code' => '372',
                'phone_code' => '353',
                'capital' => 'Dublin',
                'currency' => 'Euro',
                'currency_code' => 'EUR',
                'currency_symbol' => '€',
                'region' => 'Europe',
                'subregion' => 'Northern Europe',
                'timezone' => 'Europe/Dublin',
                'timezones' => json_encode(['Europe/Dublin']),
                'timezone_offset' => '+00:00',
                'has_dst' => true,
                'latitude' => 53.41291,
                'longitude' => -8.24389,
                'emoji' => '🇮🇪',
                'active' => true,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'name' => 'Ghana',
                'code' => 'GH',
                'code3' => 'GHA',
                'numeric_code' => '288',
                'phone_code' => '233',
                'capital' => 'Accra',
                'currency' => 'Ghanaian Cedi',
                'currency_code' => 'GHS',
                'currency_symbol' => '₵',
                'region' => 'Africa',
                'subregion' => 'Western Africa',
                'timezone' => 'Africa/Accra',
                'timezones' => json_encode(['Africa/Accra']),
                'timezone_offset' => '+00:00',
                'has_dst' => false,
                'latitude' => 7.946527,
                'longitude' => -1.023194,
                'emoji' => '🇬🇭',
                'active' => true,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'name' => 'Kenya',
                'code' => 'KE',
                'code3' => 'KEN',
                'numeric_code' => '404',
                'phone_code' => '254',
                'capital' => 'Nairobi',
                'currency' => 'Kenyan Shilling',
                'currency_code' => 'KES',
                'currency_symbol' => 'Ksh',
                'region' => 'Africa',
                'subregion' => 'Eastern Africa',
                'timezone' => 'Africa/Nairobi',
                'timezones' => json_encode(['Africa/Nairobi']),
                'timezone_offset' => '+03:00',
                'has_dst' => false,
                'latitude' => -0.023559,
                'longitude' => 37.906193,
                'emoji' => '🇰🇪',
                'active' => true,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'name' => 'Egypt',
                'code' => 'EG',
                'code3' => 'EGY',
                'numeric_code' => '818',
                'phone_code' => '20',
                'capital' => 'Cairo',
                'currency' => 'Egyptian Pound',
                'currency_code' => 'EGP',
                'currency_symbol' => 'E£',
                'region' => 'Africa',
                'subregion' => 'Northern Africa',
                'timezone' => 'Africa/Cairo',
                'timezones' => json_encode(['Africa/Cairo']),
                'timezone_offset' => '+02:00',
                'has_dst' => true,
                'latitude' => 26.820553,
                'longitude' => 30.802498,
                'emoji' => '🇪🇬',
                'active' => true,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'name' => 'Thailand',
                'code' => 'TH',
                'code3' => 'THA',
                'numeric_code' => '764',
                'phone_code' => '66',
                'capital' => 'Bangkok',
                'currency' => 'Thai Baht',
                'currency_code' => 'THB',
                'currency_symbol' => '฿',
                'region' => 'Asia',
                'subregion' => 'South-Eastern Asia',
                'timezone' => 'Asia/Bangkok',
                'timezones' => json_encode(['Asia/Bangkok']),
                'timezone_offset' => '+07:00',
                'has_dst' => false,
                'latitude' => 15.870032,
                'longitude' => 100.992541,
                'emoji' => '🇹🇭',
                'active' => true,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'name' => 'Indonesia',
                'code' => 'ID',
                'code3' => 'IDN',
                'numeric_code' => '360',
                'phone_code' => '62',
                'capital' => 'Jakarta',
                'currency' => 'Indonesian Rupiah',
                'currency_code' => 'IDR',
                'currency_symbol' => 'Rp',
                'region' => 'Asia',
                'subregion' => 'South-Eastern Asia',
                'timezone' => 'Asia/Jakarta',
                'timezones' => json_encode(['Asia/Jakarta', 'Asia/Makassar', 'Asia/Jayapura']),
                'timezone_offset' => '+07:00',
                'has_dst' => false,
                'latitude' => -0.789275,
                'longitude' => 113.921327,
                'emoji' => '🇮🇩',
                'active' => true,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'name' => 'Malaysia',
                'code' => 'MY',
                'code3' => 'MYS',
                'numeric_code' => '458',
                'phone_code' => '60',
                'capital' => 'Kuala Lumpur',
                'currency' => 'Malaysian Ringgit',
                'currency_code' => 'MYR',
                'currency_symbol' => 'RM',
                'region' => 'Asia',
                'subregion' => 'South-Eastern Asia',
                'timezone' => 'Asia/Kuala_Lumpur',
                'timezones' => json_encode(['Asia/Kuala_Lumpur', 'Asia/Kuching']),
                'timezone_offset' => '+08:00',
                'has_dst' => false,
                'latitude' => 4.210484,
                'longitude' => 101.975766,
                'emoji' => '🇲🇾',
                'active' => true,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'name' => 'Turkey',
                'code' => 'TR',
                'code3' => 'TUR',
                'numeric_code' => '792',
                'phone_code' => '90',
                'capital' => 'Ankara',
                'currency' => 'Turkish Lira',
                'currency_code' => 'TRY',
                'currency_symbol' => '₺',
                'region' => 'Asia',
                'subregion' => 'Western Asia',
                'timezone' => 'Europe/Istanbul',
                'timezones' => json_encode(['Europe/Istanbul']),
                'timezone_offset' => '+03:00',
                'has_dst' => false,
                'latitude' => 38.963745,
                'longitude' => 35.243322,
                'emoji' => '🇹🇷',
                'active' => true,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'name' => 'Poland',
                'code' => 'PL',
                'code3' => 'POL',
                'numeric_code' => '616',
                'phone_code' => '48',
                'capital' => 'Warsaw',
                'currency' => 'Polish Złoty',
                'currency_code' => 'PLN',
                'currency_symbol' => 'zł',
                'region' => 'Europe',
                'subregion' => 'Eastern Europe',
                'timezone' => 'Europe/Warsaw',
                'timezones' => json_encode(['Europe/Warsaw']),
                'timezone_offset' => '+01:00',
                'has_dst' => true,
                'latitude' => 51.919438,
                'longitude' => 19.145136,
                'emoji' => '🇵🇱',
                'active' => true,
                'created_at' => $now,
                'updated_at' => $now
            ],
            [
                'name' => 'Ukraine',
                'code' => 'UA',
                'code3' => 'UKR',
                'numeric_code' => '804',
                'phone_code' => '380',
                'capital' => 'Kyiv',
                'currency' => 'Ukrainian Hryvnia',
                'currency_code' => 'UAH',
                'currency_symbol' => '₴',
                'region' => 'Europe',
                'subregion' => 'Eastern Europe',
                'timezone' => 'Europe/Kyiv',
                'timezones' => json_encode(['Europe/Kyiv']),
                'timezone_offset' => '+02:00',
                'has_dst' => true,
                'latitude' => 48.379433,
                'longitude' => 31.16558,
                'emoji' => '🇺🇦',
                'active' => true,
                'created_at' => $now,
                'updated_at' => $now
            ],
        ];

        DB::table('countries')->insert($countries);
    }
}
